format = """
[\uE0B6](fg:#1C4961)\
[$directory](bg:#1C4961)\
[\uE0B0](fg:#1C4961 bg:#2F79A1)\
$git_branch\
$git_status\
[\uE0B0](fg:#2F79A1 bg:#3A95C7)\
$nodejs\
$rust\
$java\
[\uE0B0](#3A95C7 bg:#40A9E0)\
$cmd_duration\
[\uE0B0](#40A9E0 bg:none) \
$all$character\
"""


# Replace the "❯" symbol in the prompt with "➟"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[  ❯](bold green)"
error_symbol = "[  ✗](bold red)"

# Hide the username. The username will only show in certain scenarios
[username]
disabled = true

# configure directory
[directory]
read_only = " "
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = true # truncates directory to root folder if in github repo
#style = "bold italic cyan"
style = "bg:#1C4961 fg:white"

[git_branch]
symbol = " "
format = "[ $symbol$branch ]($style)"
style = "bg:#2F79A1 fg:white"

[git_status]
format = "[ $all_status$ahead_behind ]($style)"
style = "bg:#2F79A1 fg:white"

[cmd_duration]
min_time = 500
format = "[ \uF64F $duration ]($style)"
style = "bg:#40A9E0 fg:white"
show_notifications = true

[aws]
disabled = true

[cmake]
disabled = true

[gcloud]
disabled = true

[nodejs]
style = "bg:#3A95C7 fg:white"
format = '[[ $symbol ($version) ](bg:#3A95C7)]($style)'

[buf]
symbol = " "

[conda]
disabled = true

[crystal]
disabled = true

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "
style = "bg:#3A95C7 fg:white"
format = '[[ $symbol ($version) ](bg:#3A95C7)]($style)'

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "
style = "bg:#3A95C7 fg:white"
format = '[[ $symbol ($version) ](bg:#3A95C7)]($style)'